name: Build, Scan, and Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
    # Étape 1 : Checkout du code
    - name: Checkout code
      uses: actions/checkout@v3

    # Étape 2 : Configurer Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Étape 3 : Construire l'image Docker
    - name: Build Docker image
      run: docker build -t cheapshark-deals .

    - name: Wait before retrying Trivy scan
      run: |
            echo "Waiting for 30 seconds before retrying the scan..."
            sleep 30  # Attendre 30 secondes avant de réessayer le scan

    # Étape 4 : Scanner l'image Docker avec Trivy
    - name: Scan Docker image with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: cheapshark-deals
        format: table

    # Étape 5 : Connecter au registre GitHub Container Registry
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Étape 6 : Publier l'image Docker
    - name: Push Docker image
      run: docker push ghcr.io/t-mees/cheapshark-deals:latest
