name: Build, Scan, and publish Docker Image

on:
  push:
    branches:
      - master

jobs:
  docker-workflow:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
    - name: Fetch repository code
      uses: actions/checkout@v4

    - name: Authenticate to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Create the Docker image
      run: docker build -t ghcr.io/t-mees/cheapshark-deals:latest .

    - name: Analyze Docker image with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ghcr.io/t-mees/cheapshark-deals:latest

    - name: Upload the Docker image to the registry
      run: docker push ghcr.io/t-mees/cheapshark-deals:latest