name: Build, Scan, and Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
    # Étape 1 : Installer Docker si nécessaire
    - name: Install Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io

    # Étape 2 : Vérifier si Docker est installé
    - name: Check Docker installation
      run: docker --version

    # Étape 3 : Checkout du code
    - name: Checkout code
      uses: actions/checkout@v3

    # Étape 4 : Configurer Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Étape 5 : Construire l'image Docker
    - name: Build Docker image
      run: docker build -t cheapshark-deals .

    # Étape 6 : Scanner l'image Docker avec Trivy
    - name: Scan Docker image with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: cheapshark-deals
        format: table

    # Étape 7 : Connecter au registre GitHub Container Registry
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Étape 8 : Publier l'image Docker
    - name: Push Docker image
      run: |
        docker tag cheapshark-deals ghcr.io/t-mees/cheapshark-deals:latest
        docker push ghcr.io/t-mees/cheapshark-deals:latest
