name: Build, Scan, and publish Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.SECRET_TOKEN }}

    - name: Build the Docker image
      run: docker build -t ghcr.io/t-mees/cheapshark-deals:latest .

    - name: Wait before retrying Trivy scan
      run: |
        echo "Waiting for 30 seconds before retrying the scan..."
        sleep 30  # Attendre 30 secondes avant de réessayer le scan

    - name: Scan the Docker image with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ghcr.io/t-mees/cheapshark-deals:latest

    - name: Push the Docker image
      run: docker push ghcr.io/t-mees/cheapshark-deals:latest
